feat(09-functions): removing the sleep and error steps and finally finishing the section and workflow

diff --git a/.github/workflows/09-functions.yaml b/.github/workflows/09-functions.yaml
--- a/.github/workflows/09-functions.yaml
+++ b/.github/workflows/09-functions.yaml
@@ -1,7 +1,7 @@
 name: 09 - Using Functions
 
 on:
-  pull_request: 
+  #pull_request: 
   workflow_dispatch: 
 
 jobs:
@@ -21,17 +21,17 @@ jobs:
         if: ${{ ! cancelled() && contains(github.event.pull_request.title, 'fix') }}
         run: echo I am a bug fix
 
-      - name: Sleep for 20 seconds
-        run: sleep 20
+      # - name: Sleep for 20 seconds
+      #   run: sleep 20
 
-      - name: Failing Step
-        run: exit 1
+      # - name: Failing Step
+      #   run: exit 1
 
-      - name: I will be skipped
+      - name: I will be execute
         if: success()
         run: echo I will print if the previous steps succeed
 
-      - name: I will execute
+      - name: I will skipped
         if: failure()
         run: echo I will print if any previous step fails.
 
